### PR TITLE
Fix the issue with feather32u4 MCU

### PR DESCRIPTION
**Pull request by harshitgoel96**
Hi @colemarkham 

I found that the config for feather 32u4 has was incorrect and i have made the required changes to make it work over bluetooth.

Can you please check and see if it works ? I do not have a Meira to test it my self.

### CODE REVIEW

**Comment by colemarkham** [comment]
I appreciate the pull request. In the future, it would be better to open this on the main qmk/qmk_firmware repository. You can tag me if you think it's something I should look at. Also, in general try to ensure that a pull request only contains the change that you made. This contains all the updates from QMK master as well.

To address your particular change, the MCU definition is already set in the rules.mk file in the meira folder, so it doesn't need to be set again for the featherble. Was there some particular issue you had that required this change? Perhaps it's not the MCU line, but the BLUETOOTH=AdafruitBLE that is necessary. I will test that.

**Comment by harshitgoel96** [comment]
For bluetooth it's BLUETOOTH=AdafruitBLE But Bootloader is just an Addon. 

I added other details because the build instructions were not working and giving error due to change in QMK build script. I ultimately got it to work by setting default folder. 

I have made changes over master branch of qmk. I wanted to discuss as I don't have the board myself and did not want to add it to the main branch without your views on it. 

Sent from Yahoo Mail on Android 
 
  On Tue, 10 Apr 2018 at 10:54 PM, Cole Markham<notifications@github.com> wrote:   
I appreciate the pull request. In the future, it would be better to open this on the main qmk/qmk_firmware repository. You can tag me if you think it's something I should look at. Also, in general try to ensure that a pull request only contains the change that you made. This contains all the updates from QMK master as well.

To address your particular change, the MCU definition is already set in the rules.mk file in the meira folder, so it doesn't need to be set again for the featherble. Was there some particular issue you had that required this change? Perhaps it's not the MCU line, but the BLUETOOTH=AdafruitBLE that is necessary. I will test that.

**Comment by harshitgoel96** [comment]
The started with following thread when someone says that feather is not compatible with QMK.

YD60BLE is the only option AFAIK in 60%.

You cou...

https://www.reddit.com/r/MechanicalKeyboards/comments/896uwe/searching_for_60_bluetooth_keyboard_qmktmk/dwpjr52?utm_source=reddit-android

**Comment by harshitgoel96** [comment]
Did the config change work ? looking at the conflict, i can open up a PR in main branch directly

**Comment by colemarkham** [comment]
Yes, the required change was BLUETOOTH=AdafruitBLE.

I opened a pull request on the main repo along with some other changes: https://github.com/qmk/qmk_firmware/pull/2731

**Comment by harshitgoel96** [comment]
awesome. thanks. 👍

**Pull request closed without merging**
